development:
  adapter: postgresql
  encoding: unicode
  username: simontoh
  password: 
  database: pgdb_development
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: pgdb_test
  pool: 5
  username: simontoh
  host: localhost
  password:
  timeout: 5000

